Update Dockerfile: adding `less`
Adding `less`. When running this image in GitHub codespaces in github.com/Azure/terraform-azurerm-aks it is now not possible to type `git diff` the command fails because `less` is missing

```
root [ /workspaces/terraform-azurerm-aks ]# git diff
error: cannot run less: No such file or directory
```

To fix the problem now I have to do `yum install less`